### ISSUE TITLE
Any chance of bulidng an Ipa for us who can only sideload without a mac?

### ISSUE THREAD

**Issue by Bitwolfies** [jellyfin-archive/jellyfin-client-ios#10]
Dont have a mac but I would love to test this out and I can sideload ipas, cant build them though, no access to a mac, any chance we can get a pre built one?

**Comment by anthonylavado** [comment]
@Darkwolf1515 So the whole process is tricky. I'd imagine you'd have to break/replace the signature, because otherwise there's no way you'll get it on (even if I use our developer license to build it).

As it is right now, the app also doesn't do too much. It will playback some video, but not all options are present. It shows music, but fails to play it right now.

There's no advantage to using this app just yet. We'll have to see if we can still try to get any contributors, or if we'll have to archive it too. The other app (Expo) is starting to make some strides (yet to be released), and we're exploring options for "ejecting". That's where you only use Expo as a base and can bring in other features - namely native music playback, and trying to add Casting.

**Comment by Bitwolfies** [comment]
Right thank you for responding, but I have to ask, how was https://github.com/leinelissen/jellyfin-audio-player able to release an ipa without tying it to his license, I got it to run just fine on my phone.

Anyways, thanks for the time, I hope you can get more contributors here, as native always feels better than a wrapper!

**Comment by ghost** [comment]
Can't you just install via the app store?

**Comment by ghost** [comment]
Is the app not being worked on any more? Has is been abandoned?

**Comment by ghost** [comment]
> Dont have a mac but I would love to test this out and I can sideload ipas, cant build them though, no access to a mac, any chance we can get a pre built one?

If you're able to jailbreak your iPhone, you can use something called "ReProvision" to install IPAs which will auto-resign every 7 days(without a dev account) no computer required. If you have a Windows 10 machine, there's also something called [AltStore](https://altstore.io/) which does the exact same thing, no jailbreak required, but the computer will have to be on at least every 7 days to resign the app(this one just requires a PC to do).

Edit: nevermind, it appears you just can't sign.

**Comment by Bitwolfies** [comment]
> 
> 
> Is the app not being worked on any more? Has is been abandoned?

This is a separate ios app, not the one in the app store, that one is known as the "expo" client, this is a native one for ios built in swift, I just wanted to test it, and yes, I use alt store. My issue was I cannot get the ipa itself without a mac.

**Comment by ghost** [comment]
I don't know exactly your situation atm, but I'm thinking of two solutions if you're just not able to sign:
1. Use AltStore on Windows 10, if you have it.
2. Jailbreak with unc0ver, no PC needed(check out r/jailbreak on Reddit), and install ReProvision, which gives you on-device signing. Then you can download the IPA for the swift client and sign in from your device.

**Comment by Bitwolfies** [comment]
> I don't know exactly your situation atm, but I'm thinking of two solutions if you're just not able to sign:
> 
> 1. Use AltStore on Windows 10, if you have it.
> 2. Jailbreak with unc0ver, no PC needed(check out r/jailbreak on Reddit), and install ReProvision, which gives you on-device signing. Then you can download the IPA for the swift client and sign in from your device.

I can sideload ipas just fine, my issue, is that I cannot make the ipa, without a Mac.

**Comment by ghost** [comment]
It appears that there's a build under "releases" now, I'll be trying it out myself today, 'cause you gotta know your options

**Comment by Bitwolfies** [comment]
> It appears that there's a build under "releases" now, I'll be trying it out myself today, 'cause you gotta know your options

If there is, I can’t see them.

**Comment by ghost** [comment]
It's available here: https://github.com/leinelissen/jellyfin-audio-player/releases/tag/v0.0.1-alpha1
Try viewing the original link you provided on Desktop, might see it then.

**Comment by ghost** [comment]
Just did some testing on it, make sure you click "set server" to actually set up your server.

**Comment by ghost** [comment]
Sorry for any confusion on this all, but it looks like originally you wanted an IPA for the official iOS client? If so, again, there's the App Store :wink: 
If you're looking for the Swift client, it's available via the link provided above.

I honestly don't know how that guy did it without a Mac. Maybe he got someone to build it for him, idk, I'll look into it.

**Comment by Bitwolfies** [comment]
Let me just break this down.

-I asked for the Jellyfin swift client to release an ipa, because the unofficial Jellyfin Audio iOS player did

-you said to install via AppStore, this is not the same app as the iOS store version, it’s a new one built in swift

-you then told me how to sideload, something I know how to do

-then said there was a new release for the audio client, not the swift client which where we are, and what I thought you meant. 

-you clarified after you realized I meant for this one, which you then said install from AppStore, but this is not the same as the one on AppStore.

**Comment by anthonylavado** [comment]
This client is stalled, and as I said, it really doesn't do anything better than the current Expo client.

If works starts on this again, I'll consider building the IPA. Right now, it's not worth it.

**Comment by ghost** [comment]
Just found something called [Theos](https://github.com/theos/theos), was recommended it on r/Jailbreak, might help with building apps. I don't really know how it works, you can ask on r/Jailbreak for more assistance(note that if you do take this route, you'll have to Jailbreak your device, voiding your warrently). 

I'm still slightly confused anyway... that third partly client that we were talking about has an IPA available, still a bit confused why/if you need to build an IPA.

**Comment by Bitwolfies** [comment]
im going to cry

**Comment by ghost** [comment]
Hope it's tears of joy lol(can't tell).

**Comment by Bitwolfies** [comment]
"hey jellyfin team, can you release an ipa for https://github.com/jellyfin/jellyfin-client-ios , I would like you to as https://github.com/leinelissen/jellyfin-audio-player has released one! Meaning its possible to build ipas, for those of us who are able to sideload, yet do not possess macs! I would like this since this version is not the same as the current one on the app store! The one on the appstore is https://github.com/jellyfin/jellyfin-expo , not the same as the app here!"

I have no idea how else I can explain this.

**Comment by anthonylavado** [comment]
Fine, I'll make one - but be ready for absolute disappointment. I'm serious when I say it's not worth using yet.

**Comment by anthonylavado** [comment]
@hwittenborn The user is talking about this specific app, not any others. They were just mentioning the other one as a an example. (Also @Darkwolf1515, for reference, building with React/Native and Expo allow you to create IPAs, even if they're not properly signed. That's why they could create a release without a full Developer License.)

**Comment by ghost** [comment]
Sorry if I’m nagging anything on, but I think this is what you want: an IPA for this client, in this repo, which is maintained by the Jellyfin team.
It looks like you’re saying the App Store variant is different? That might be the case, I wouldn’t know.

**Comment by anthonylavado** [comment]
Yes. This is not the app that's on the app store. That is https://github.com/jellyfin/jellyfin-expo/. I apologize for the confusion 😅

**Comment by anthonylavado** [comment]
Current Known Issues:
- Any video content that requires transcoding will have audio only, the video will not show. This is due to stream changes in 10.6.x.
- When a video begins playing, it will continue playing in the background. This persists even if you dismiss the card by going back to the library or swiping away, or going to the home screen. You can only hear the audio, you cannot restore the video feed. The only way to stop playing is to either remember to pause the video before dismissing it, or go to another item detail page, or force close the app.
- Music libraries will be displayed, but music will not play. 
- There is no quick alphabetical access or sorting in the library screens. You must scroll through all items in an A-Z list.
- Live TV will appear as a library if configured, but no channels will appear and it will not play.
- There is no way to organize the home screen at this time.
- The download function does not work if the video is in an incompatible format or requires transcoding. It will only work with perfectly formatted videos (e.g. H264, in an MP4, with AAC/MP3 audio).

**Comment by anthonylavado** [comment]
Here is the IPA as requested: https://github.com/jellyfin-archive/jellyfin-client-ios/releases/tag/v0.0.1

**Comment by Bitwolfies** [comment]
> 
> 
> Fine, I'll make one - but be ready for absolute disappointment. I'm serious when I say it's not worth using yet.

 Sorry, you seem a tad annoyed with me, I gave up on it awhile ago and was just trying to explain what I was requesting, but Ill download it and play around with it, thanks for your time.

**Comment by Bitwolfies** [comment]
> 
> 
> Current Known Issues:
> 
>     * Any video content that requires transcoding will have audio only, the video will not show. This is due to stream changes in 10.6.x.
> 
>     * When a video begins playing, it will continue playing in the background. This persists even if you dismiss the card by going back to the library or swiping away, or going to the home screen. You can only hear the audio, you cannot restore the video feed. The only way to stop playing is to either remember to pause the video before dismissing it, or go to another item detail page, or force close the app.
> 
>     * Music libraries will be displayed, but music will not play.
> 
>     * There is no quick alphabetical access or sorting in the library screens. You must scroll through all items in an A-Z list.
> 
>     * Live TV will appear as a library if configured, but no channels will appear and it will not play.
> 
>     * There is no way to organize the home screen at this time.
> 
>     * The download function does not work.

And funnily enough, downloading works for me, at least on videos.

**Comment by anthonylavado** [comment]
> And funnily enough, downloading works for me, at least on videos.


Fixed:
> - The download function does not work if the video is in an incompatible format or requires transcoding. It will only work with perfectly formatted videos (e.g. H264, in an MP4, with AAC/MP3 audio)

---

> Sorry, you seem a tad annoyed with…

Actually, I apologize. It was a bad weekend (personally) and it wasn't your fault. I guess I'm just also frustrated by a small roadblock in trying to make Jellyfin better, but we've got some plans and things to look forward to. I won't spoil the surprise yet.

**Comment by Bitwolfies** [comment]
> 
> 
> > And funnily enough, downloading works for me, at least on videos.
> 
> Fixed:
> 
> > * The download function does not work if the video is in an incompatible format or requires transcoding. It will only work with perfectly formatted videos (e.g. H264, in an MP4, with AAC/MP3 audio)
> 
> > Sorry, you seem a tad annoyed with…
> 
> Actually, I apologize. It was a bad weekend (personally) and it wasn't your fault. I guess I'm just also frustrated by a small roadblock in trying to make Jellyfin better, but we've got some plans and things to look forward to. I won't spoil the surprise yet.

Hey, its no issue, and it did seem like things were a bit slower this week, I wonder what the issue is, anyways, I hope obvious enough surprise that I know it when you announce the feature! Thanks for volunteering your time to maintain all of this.
