### ISSUE TITLE
[Request] Make the loop button's color scheme follow that of the shuffle button

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-client-ios#12]
**Directions**
1. Start a queue of music, click shuffle and loop.

The shuffle button will be blue(in my case), but the loop button just gets a more white-y color. It would be better to see it just turn blue. Feel free to experiment with the 1 for a single loop on being blue(in this case) or white.

**Comment by anthonylavado** [comment]
Is this meant for the released version, which is [Jellyfin Expo](https://github.com/jellyfin/jellyfin-expo/)? If so, I can move the issue for you 🙂

The UI is from the Web Client, so I might need to move it to [Jellyfin-Web](https://github.com/jellyfin/jellyfin-web/).

**Comment by ghost** [comment]
Hey, commenting again!
As per another of my comments, this issue is only present in the mobile apps, but not when accessing via a browser.

**Comment by anthonylavado** [comment]
When you say browser, you mean browser on a desktop computer? It's all the same web interface, but it has layout changes based on the size of the screen ;-)
 I'll move it to web.

**Comment by ghost** [comment]
You can I guess, but again, this issue is only in the app, not when visiting the website. My guess is that the iOS client has some stuff that looks like the web GUI but isn't directly pulling from it, but rather from local files from being baked into the app. Though I wouldn't know, I haven't looked at the source code yet.

**Comment by anthonylavado** [comment]
The iOS pulls the web client directly from the server, it doesn't have any of that baked in to it. I'be finally got some time so I can move/create these issues for you.

**edit:** the "home" and "settings" tabs at the bottom, and the whole "settings" screen are custom to the iOS app, but everything else (player, browsing), is all directly a webview to your server.
