### ISSUE TITLE
[Request] Add shuffle button for libraries.

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-client-ios#13]
For example, on my music library, there's no apparent way to shuffle all of my music besides going to "Songs" --> first song, Play all from here --> bring up player --> hit shuffle button.

On the desktop client anyway, you can just click the three dots on a library and hit "Shuffle". There is a three-dots menu on the iOS client if you hold on the library, after which it'll appear in the top right, but a shuffle button lacks to appear there.

**Comment by anthonylavado** [comment]
Is this meant for the released version, which is [Jellyfin Expo](https://github.com/jellyfin/jellyfin-expo/)? If so, I can move the issue for you 🙂

The UI is from the Web Client, so I might need to move it to [Jellyfin-Web](https://github.com/jellyfin/jellyfin-web/).

**Comment by ghost** [comment]
You may want to, I don't know, the issue is only present in the mobile app though.
Check my other comment for more info.
