### ISSUE TITLE
TestFlight version ?

### ISSUE THREAD

**Issue by Ribero** [jellyfin-archive/jellyfin-client-ios#15]
Hi @anthonylavado ,

Is there a Testflight version of the app to test it out or is a bit too early ?

**Comment by anthonylavado** [comment]
This app is largely stalled and doesn't do much at the moment (see this [list of issues](https://github.com/jellyfin-archive/jellyfin-client-ios/issues/10#issuecomment-675064350)). As a result, there is no version for testing unless you compile one yourself.

Sorry ☹️
